version: "3.9"
services:
  # The FastAPI Web Server
  web:
    build: .
    env_file:
      - .env

    #user: "1000:1000"
    ports:
      - "6969:8000"
    volumes:
      # Mount local directories and files into the container for persistence
      - ./uploads_data:/app/uploads
      - ./processed_data:/app/processed

volumes:
  uploads_data: {}
  processed_data: {}
