auth_settings:
  oidc_client_id: filewiz
  oidc_client_secret:
  oidc_server_metadata_url: https://accounts.example.com/oidc/.well-known/openid-configuration
  oidc_userinfo_endpoint: https://accounts.example.com/oidc/me
  oidc_end_session_endpoint: https://accounts.example.com/oidc/session/end
  admin_users:
  - user@example.com
webhook_settings:
  enabled: False
  allow_chunked_api_uploads: False
  allowed_callback_urls: []
  callback_bearer_token:
tts_settings: 
  piper: 
    model_dir: "./models/tts"
    use_cuda: False 
    synthesis_config: 
      length_scale: 1.0
      noise_scale: 0.667 
      noise_w: 0.8
  kokoro: 
    model_dir: "./models/tts/kokoro"
    command_template: "kokoro-tts {input} {output} --model {model_path} --voices {voices_path} --voice {model_name}"

app_settings:
  max_file_size_mb: '2000'
  # app_public_url: "http://localhost:8000" # Uncomment and set to your public URL if downloads don't work correctly
  allowed_all_extensions:
  - .aac
  - .aiff
  - .avif
  - .avi
  - .azw3
  - .bmp
  - .csv
  - .dbf
  - .doc
  - .docx
  - .dpx
  - .dxf
  - .eps
  - .epub
  - .fb2
  - .fits
  - .flac
  - .flv
  - .gif
  - .gsm
  - .html
  - .htmlz
  - .ico
  - .jpeg
  - .jpg
  - .jxl
  - .lit
  - .lrf
  - .m4a
  - .md
  - .mkv
  - .mobi
  - .mov
  - .mp3
  - .mp4
  - .odt
  - .ogg
  - .ogv
  - .opml
  - .opus
  - .pdb
  - .pdf
  - .pnm
  - .png
  - .ppt
  - .pptx
  - .ps
  - .rst
  - .rtf
  - .svg
  - .tcr
  - .tex
  - .tif
  - .tiff
  - .txt
  - .wav
  - .webm
  - .webp
  - .wma
  - .wmv
  - .wps
  - .xlsx
  - .xls
  - .xml
  - .xpm
  - .zip
ocr_settings:
  ocrmypdf:
    deskew: true
    clean: true
    optimize: 1
    force_ocr: true
academic_settings:
  pandoc:
    csl_files:
      apa: https://www.zotero.org/styles/apa
      mla: https://www.zotero.org/styles/modern-language-association
      chicago: https://www.zotero.org/styles/chicago-author-date
      chicago-fullnote: https://www.zotero.org/styles/chicago-fullnote-bibliography
transcription_settings:
  whisper:
    compute_type: int8
    # device: cuda 
    # device_index: 0
    allowed_models:
    - tiny
    - base
    - small
    - medium
    - large-v3
    - distil-large-v2
conversion_tools:
  libreoffice:
    name: LibreOffice
    command_template: libreoffice --headless --convert-to {filter} --outdir {output_dir}
      {input}
    timeout: 300
    filters:
      pdf: pdf
      docx: docx
      doc: doc
      odt: odt
      html: html
      rtf: rtf
      txt: txt:Text
      xml: xml
      epub: epub
      xlsx: xlsx
      xls: xls
      ods: ods
      csv: csv:Text
      pptx: pptx
      ppt: ppt
      odp: odp
      svg: svg
      png: png
      jpg: jpg
      wps: wps
      dbf: dbf
    formats:
      pdf: PDF Document
      docx: Word Document (DOCX)
      doc: Word 97-2003 Document (DOC)
      odt: OpenDocument Text
      html: HTML Document
      rtf: Rich Text Format
      txt: Plain Text
      xml: Word 2003 XML
      epub: EPUB E-Book
      xlsx: Excel Spreadsheet (XLSX)
      xls: Excel 97-2003 Spreadsheet (XLS)
      ods: OpenDocument Spreadsheet
      csv: CSV
      pptx: PowerPoint Presentation (PPTX)
      ppt: PowerPoint 97-2003 Presentation (PPT)
      odp: OpenDocument Presentation
      svg: SVG Image (from Draw/Impress)
      png: PNG Image (from Draw/Impress)
      jpg: JPEG Image (from Draw/Impress)
      wps: MS Works Document
      dbf: dBase Database File
  pandoc:
    name: Pandoc
    command_template: pandoc --standalone {input} -o {output} --to={output_ext} --pdf-engine=xelatex
    timeout: 300
    formats:
      docx: Word Document
      odt: OpenDocument Text
      pdf: PDF Document
      rtf: Rich Text Format
      txt: Plain Text
      md: Markdown (Strict)
      gfm: Markdown (GitHub-Flavored)
      tex: LaTeX
      html: HTML5
      epub: EPUB v3 Book
      epub2: EPUB v2 Book
      pptx: PowerPoint Presentation
      beamer: Beamer PDF Slides
      slidy: Slidy HTML Slides
      revealjs: reveal.js HTML Slides
      rst: reStructuredText
      jira: Jira Wiki Markup
      mediawiki: MediaWiki Markup
      asciidoc: AsciiDoc
      textile: Textile
      opml: OPML
      man: Groff Man Page
      docbook: DocBook XML
  ghostscript_pdf:
    name: Ghostscript (PDF)
    command_template: gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dNOPAUSE -dQUIET
      -dBATCH {preset} -sOutputFile={output} {input}
    timeout: 60
    formats:
      screen: PDF (Optimized for Screen)
      ebook: PDF (Optimized for Ebooks)
      printer: PDF (Optimized for Print)
      prepress: PDF (Optimized for Prepress)
      pdfa: PDF/A-2b (for Archiving)
  ghostscript_image:
    name: Ghostscript (Image)
    command_template: gs -dNOPAUSE -dBATCH -sDEVICE={device} -r{dpi} -sOutputFile={output}
      {input}
    timeout: 60
    formats:
      jpeg_72: JPEG Image (72 DPI)
      jpeg_150: JPEG Image (150 DPI)
      jpeg_300: JPEG Image (300 DPI)
      png16m_150: PNG Image (150 DPI)
      png16m_300: PNG Image (300 DPI)
      pngalpha_150: PNG Image with Alpha (150 DPI)
      pngalpha_300: PNG Image with Alpha (300 DPI)
      tiff24nc_300: TIFF Image (300 DPI)
      tiff24nc_600: TIFF Image (600 DPI)
      tiffg4_300: TIFF Image (G4 Fax, 300 DPI)
      bmp16m_300: BMP Image (300 DPI)
      pcx24b_300: PCX Image (300 DPI)
      pnm_300: PNM Image (300 DPI)
  calibre:
    name: Calibre (ebook-convert)
    command_template: ebook-convert {input} {output}
    timeout: 600
    formats:
      epub: EPUB
      mobi: MOBI
      azw3: Amazon Kindle (AZW3)
      pdf: PDF
      docx: Word Document
      rtf: Rich Text Format
      txt: Plain Text
      fb2: FictionBook 2
      htmlz: Zipped HTML
      pdb: eReader PDB
      lrf: Sony BroadBand eBook
      lit: Microsoft Reader
      tcr: Psion Series 3
  ffmpeg:
    name: FFmpeg
    command_template: ffmpeg -i {input} -y -preset medium {output}
    timeout: 600
    formats:
      mp4: MP4 Video (H.264/AAC)
      mp4_hevc: MP4 Video (H.265/AAC)
      mkv: MKV Video (H.264/AAC)
      mov: MOV Video (H.264/AAC)
      webm: WebM Video (VP9/Opus)
      webm_av1: WebM Video (AV1/Opus)
      avi: AVI Video (MPEG4/MP3)
      wmv: WMV Video
      flv: FLV Video (Flash)
      ogv: Ogg Theora Video
      mp3: MP3 Audio
      wav: WAV Audio (Uncompressed PCM)
      flac: FLAC Audio (Lossless)
      aac: AAC Audio
      aiff: AIFF Audio
      wma: WMA Audio
      ogg: Ogg Vorbis Audio
      opus: Opus Audio
      gif: Animated GIF
      apng: Animated PNG
  vips:
    name: VIPS
    command_template: vips copy {input} {output}[Q=90]
    timeout: 60
    formats:
      jpg: JPEG Image (Q90)
      png: PNG Image
      webp: WebP Image (Q90)
      tiff: TIFF Image
      avif: AVIF Image (Q90)
      heif: HEIF Image (Q90)
      jp2: JPEG 2000
      gif: GIF Image
      pnm: PNM Image
      fits: FITS Image
  graphicsmagick:
    name: GraphicsMagick
    command_template: gm convert {input} -quality 90 {output}
    timeout: 60
    formats:
      jpg: JPEG Image (Q90)
      png: PNG Image
      webp: WebP Image
      tiff: TIFF Image
      gif: GIF Image
      bmp: BMP Image
      pdf: PDF from Images
      eps: Encapsulated PostScript
      dpx: DPX Image
      ico: Windows Icon
      xpm: X PixMap
  inkscape:
    name: Inkscape
    command_template: inkscape {input} --export-filename={output}
    timeout: 30
    formats:
      svg: SVG (Plain)
      inkscape_svg: SVG (Inkscape)
      png_96: PNG Image (96 DPI)
      png_300: PNG Image (300 DPI)
      pdf: PDF Document
      eps: Encapsulated PostScript
      ps: PostScript
      emf: Enhanced Metafile
      wmf: Windows Metafile
      dxf: AutoCAD DXF R14
  libjxl:
    name: libjxl (cjxl)
    command_template: cjxl {input} {output} -q 90
    timeout: 30
    formats:
      jxl_q90: JPEG XL (Quality 90)
      jxl_lossless: JPEG XL (Lossless)
      jxl_hq: JPEG XL (High Compression)
  resvg:
    name: resvg
    command_template: resvg {input} {output}
    timeout: 30
    formats:
      png: PNG from SVG
  potrace:
    name: Potrace
    command_template: potrace {input} --svg -o {output}
    timeout: 30
    formats:
      svg: SVG from Bitmap
      pdf: PDF from Bitmap
      eps: EPS from Bitmap
      ps: PostScript from Bitmap
      dxf: DXF from Bitmap
  markitdown:
    name: Markitdown
    command_template: markitdown {input} -o {output}
    timeout: 300
    formats:
      md: Markdown from Everything!
  pngquant:
    name: pngquant
    command_template: pngquant --quality={quality} --speed {speed} --force --output
      {output} {input}
    timeout: 300
    formats:
      png_hq: PNG (High Quality Compression)
      png_mq: PNG (Medium Quality Compression)
      png_fast: PNG (Fast Compression)
  sox:
    name: SoX Audio Converter
    command_template: sox {input} -r {samplerate} {bitdepth} {output}
    timeout: 600
    formats:
      wav_48k_24b: WAV (48kHz, 24-bit)
      wav_44k_16b: WAV (CD, 44.1kHz, 16-bit)
      wav_16k_16b: WAV (Voice, 16kHz, 16-bit)
      flac_48k_24b: FLAC (48kHz, 24-bit)
      flac_44k_16b: FLAC (CD, 44.1kHz, 16-bit)
      aiff_44k_16b: AIFF (CD, 44.1kHz, 16-bit)
      mp3_320k: MP3 (320 kbps)
      mp3_128k: MP3 (128 kbps)
      ogg_192k: Ogg Vorbis (192 kbps)
      ogg_96k: Ogg Vorbis (96 kbps)
      opus_128k: Opus (128 kbps)
      opus_64k: Opus (64 kbps, Voice)
      gsm: GSM 06.10 (13kbps, Voice)
  mozjpeg:
    name: MozJPEG
    command_template: cjpeg -quality {quality} -outfile {output} {input}
    timeout: 30
    formats:
      jpg_q85: JPEG (High Quality)
      jpg_q75: JPEG (Web Quality)
      jpg_q60: JPEG (Aggressive Compression)
  pandoc_academic:
    name: Pandoc (Academic Document)
    command_template: "pandoc {main_document} -o {output} --bibliography {bib_file} --citeproc --csl {csl_style}"
    timeout: 300
    formats:
      pdf_apa: "PDF with Bibliography (APA Style)"
      pdf_mla: "PDF with Bibliography (MLA Style)"
      pdf_chicago: "PDF with Bibliography (Chicago Style)"
      pdf_chicago_fullnote: "PDF with Bibliography (Chicago Full Note)"
